### ISSUE TITLE
Posibility to add custom names for files

### ISSUE THREAD

**Issue by zachari043** [Jonathan-Greve/GuildWarsMapBrowser#10]
Will be cool to add the ability to edit and customize the human readable name on files. saved in an external file...

**Comment by Jonathan-Greve** [comment]
Agreed. Perhaps one day we could have the whole .dat mapped with proper names then! Or at the very least it makes it easier to bookmark points of interest.

I'll see to it.

**Comment by robkolven** [comment]
Would also love for this!! Along with this add new Types. (ex: Map-Outpost, Map-Explorable, Map-PvP)

**Comment by Jonathan-Greve** [comment]
> Would also love for this!! Along with this add new Types. (ex: Map-Outpost, Map-Explorable, Map-PvP)

Good idea. There is already a PvP column in the dat browser. But I'll make sure to include it when adding the ability to add custom names for files. Also be aware that many maps are used for both the outpost and the explorable area; for example Lakeside County, but I think it's still a good idea to allow people to include. Then some maps might have both flags (i.e. both Outpost and Explorable) while others would only have one of them.

I'm still thinking about format for the file that should contain the custom info. .csv might be easy and something most people is familiar with.

**Comment by robkolven** [comment]
I have noticed that about the Outposts. Some areas are used for cinematics as well. Found some interesting early development explorable zones.
I’d say .csv would be the most compatible too if they want to use it in another program.
