### ISSUE TITLE
All version 5.x versions crashes at start up. Version 4.7 opens fine

### ISSUE THREAD

**Issue by Miniputs** [Jonathan-Greve/GuildWarsMapBrowser#11]
All version 5.x versions crashes at start up. Version 4.7 opens fine.
Only installed the .exe file not the blender files. The window frame with title shows up with no content in window.
Only version 4.7 and below generates imgui.ini file

System:
Windows 10, 16 GB Ram
GPU: AMD Radeon RX 6400 4 GB Ram
CPU/APU: AMD A8-7600 Radeon R7

**Comment by Jonathan-Greve** [comment]
Thanks for the report. I'll look into it and add error reporting in a future release.

**Comment by Miniputs** [comment]
Using version 5.1 and attached image of resulting error:
![GWMB51error](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/assets/53795477/fa7df442-8728-4fe6-9843-98e89f4f14cb)

**Comment by Jonathan-Greve** [comment]
Hi could you try version 5.1.1 that I released yesterday. Hopefully it'll work but otherwise please let me know.

**Comment by Miniputs** [comment]
Almost same error in 5.1.1:
![GWMB511error](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/assets/53795477/05c641c7-411f-4f31-b712-5e2b512a50c6)

**Comment by Jonathan-Greve** [comment]
Ah damn. But thanks for checking. 

I've uploaded two versions of the program [here](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/releases/tag/5.1.1_debug) which should create a minidump when it crashes. 

Please try running `GuildWarsMapBrowser_debug.exe first` and upload the 'CrashDump.dmp' file here (the .dmp file should be created in the same folder as the .exe and only be a few MBs big).

If for some reason `GuildWarsMapBrowser_debug.exe` doesn't crash then use `GuildWarsMapBrowser_release.exe` instead.

**Comment by Miniputs** [comment]
[CrashDump.dmp](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/files/13693175/CrashDump.dmp)

**Comment by Jonathan-Greve** [comment]
Thanks for sticking with me. That was a huge help and hopefully I've fixed it now. It seems I messed up some code when applying MSAA. This new version reverts that part of the code back to how it was prior to release of v5.

Please try it out [here](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/releases/tag/v5.1.1_bug_fix0).

If it's fixed for you I'll push a new stable release.

**Comment by Miniputs** [comment]
It works fine now. Also verified that it opens GW.dat file fine.
Thanks a lot. To me the issue is solved.

**Comment by Jonathan-Greve** [comment]
Fixed in [cf814e0](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/commit/cf814e0a87169482a5d2b043d6a627886eab2036) and added to release of [v5.1.2](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/releases/tag/v5.1.2)
