### ISSUE TITLE
Crash when trying to open map with ID 115265

### ISSUE THREAD

**Issue by Miniputs** [Jonathan-Greve/GuildWarsMapBrowser#13]
Crash when trying to open map with ID 115265.
Previous map ID: 114388.
My PC is slow so I may have pressed it hard.
The crash file ended up where I export my models.

[CrashDump.dmp](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/files/13694405/CrashDump.dmp)

**Comment by Jonathan-Greve** [comment]
Oh yeah makes sense that the CrashDump is saved to the models folder. I haven't told it to use the .exe path so it just uses the last known path by default. I'll fix that in the next release.

Could you also try the newest release [here](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/releases/tag/v5.1.2) it should also be many times faster than the debug built you used.

Also if possible could you provide the File ID (the second column in the dat browser) as well as the murmur3 (last column).

**Comment by Miniputs** [comment]
File ID: 0x5CFA5 (380837)
murmur3: 3486048501
I can not repeat the error in 5.1.2 and in version 5.1.1 Fix debug I can only repeat when switching between maps with file ID : 0x5CFC6 (380870) and File ID: 0x5CFA5 (380837). So maybe it is solved

**Comment by Jonathan-Greve** [comment]
OK I'll close it for now. Feel free to repopen or create a new issue if you run into randow crashes again.
